/**
 * Loads the Top 250 dataset that ships with the site.
 *
 * movies.json is generated by scripts/fetch-top250.mjs and committed, so the page needs no
 * API key and no network round-trip beyond its own assets.
 */

const DATA_URL = new URL('../movies.json', import.meta.url);

/**
 * Fallback if movies.json is somehow missing. The upstream source sends
 * `access-control-allow-origin: *`, so this works from the browser.
 */
const FALLBACK_URL =
  'https://raw.githubusercontent.com/movie-monk-b0t/top250/master/top250_min.json';

function fromFallbackShape(raw) {
  return raw
    .map((m) => ({
      id: (m.imdb_url || '').match(/tt\d+/)?.[0] || '',
      title: (m.name || '').trim(),
      year: Number.parseInt(m.year, 10) || null,
      rating: Number.parseFloat(m.rating) || null,
      genres: Array.isArray(m.genre) ? m.genre : [],
      directors: Array.isArray(m.directors) ? m.directors : [],
      actors: Array.isArray(m.actors) ? m.actors.slice(0, 3) : [],
      plot: (m.desc || '').trim(),
      thumb: m.thumb_url || '',
      poster: (m.image_url || '').replace(/\._V1_.*?\.jpg$/i, '._V1_UX500.jpg'),
    }))
    .filter((m) => m.id)
    .sort((a, b) => b.rating - a.rating);
}

export function decadeOf(year) {
  if (!Number.isFinite(year)) return 'Unknown';
  return `${Math.floor(year / 10) * 10}s`;
}

/** @returns {Promise<Array>} normalized movies, each with a stable `tt…` id. */
export async function loadMovies() {
  try {
    const res = await fetch(DATA_URL);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    const movies = Array.isArray(data) ? data : data.movies;
    if (!Array.isArray(movies) || !movies.length) throw new Error('empty dataset');
    return movies.map((m) => ({ ...m, decade: decadeOf(m.year) }));
  } catch (err) {
    console.warn('movies.json unavailable, falling back to upstream source:', err.message);
    const res = await fetch(FALLBACK_URL);
    if (!res.ok) throw new Error(`Could not load movie data (HTTP ${res.status})`);
    const movies = fromFallbackShape(await res.json());
    return movies.map((m) => ({ ...m, decade: decadeOf(m.year) }));
  }
}

export function imdbUrl(id) {
  return `https://www.imdb.com/title/${id}/`;
}

/** Sorted unique genre list, for the filter UI. */
export function allGenres(movies) {
  return [...new Set(movies.flatMap((m) => m.genres))].sort();
}

/** Decades present in the data, newest first. */
export function allDecades(movies) {
  return [...new Set(movies.map((m) => m.decade))].sort(
    (a, b) => Number.parseInt(b, 10) - Number.parseInt(a, 10)
  );
}
